#!/bin/bash
# Build the Motorola MH7021 OpenWrt image. Run ON NEON after apply.sh:
#     ~/lab/owrt/mh7021/build_mh7021.sh                          # tree ~/lab/owrt/openwrt (main)
#     T=~/lab/owrt/openwrt-25.12 ~/lab/owrt/mh7021/build_mh7021.sh   # release worktree (signed)
# First build of a tree: feeds + toolchain, ~1 h on 12 cores. Later builds are incremental.
# Signing: the usign key pair key-build/key-build.pub(.ucert) is generated in the tree once
# (KEEP key-build PRIVATE; it is what makes the images/sha256sums "ours"); the apk key pair
# private-key.pem/public-key.pem is generated by the build itself. Both public keys are
# baked into the image, so units verify our packages and OpenWrt's official ones.
# Outputs: $T/bin/targets/ipq40xx/generic/openwrt-*-motorola_mh7021-* (+ .sig, sha256sums.sig)
set -e; cd ~/lab/owrt
T=${T:-~/lab/owrt/openwrt}; NAME=$(basename $T)
# a worktree's .git is a pointer into the main repo, so mount that repo's .git at its host path too;
# VER = the exact tag (if any) -> CONFIG_VERSION_NUMBER, so /etc/apk/repositories points at the matching official feed
VER=$(git -C $T describe --tags --exact-match 2>/dev/null | sed 's/^v//' || true)
docker run --rm --name owrt-build-$NAME --user $(id -u):$(id -g) -e HOME=/src -e VER="$VER" \
  -v $T:/src -v ~/lab/owrt/openwrt/dl:/src/dl -v ~/lab/owrt/openwrt/.git:$HOME/lab/owrt/openwrt/.git:ro \
  -w /src owrt-build bash -c '
  set -e -o pipefail
  [ -d feeds/packages ] || { echo "== feeds"; ./scripts/feeds update -a >/dev/null && ./scripts/feeds install -a >/dev/null; }
  [ -s .config ] || cat > .config <<CFG
CONFIG_TARGET_ipq40xx=y
CONFIG_TARGET_ipq40xx_generic=y
CONFIG_TARGET_ipq40xx_generic_DEVICE_motorola_mh7021=y
CONFIG_TARGET_ROOTFS_INITRAMFS=y
CONFIG_PACKAGE_luci=y
CONFIG_PACKAGE_wpad-mesh-mbedtls=y
# CONFIG_PACKAGE_wpad-basic-mbedtls is not set
CONFIG_SIGNED_PACKAGES=y
CONFIG_SIGNATURE_CHECK=y
CFG
  sed -i "/CONFIG_TARGET_ipq40xx_generic_DEVICE_glinet_gl-b2200/d" .config
  grep -q "DEVICE_motorola_mh7021=y" .config || echo "CONFIG_TARGET_ipq40xx_generic_DEVICE_motorola_mh7021=y" >> .config
  # CONFIG_VERSION_NUMBER only survives defconfig with CONFIG_VERSIONOPT=y
  # (VERSIONOPT is only settable under IMAGEOPT)
  if [ -n "$VER" ]; then sed -i "/CONFIG_IMAGEOPT/d; /CONFIG_VERSIONOPT/d; /CONFIG_VERSION_NUMBER/d" .config; printf "CONFIG_IMAGEOPT=y\nCONFIG_VERSIONOPT=y\nCONFIG_VERSION_NUMBER=\"%s\"\n" "$VER" >> .config; fi
  make defconfig >/dev/null
  make package/firmware/ipq-wifi/clean >/dev/null 2>&1 || true   # force prepare, so the local board files are copied in
  grep -E "DEVICE_motorola_mh7021|PACKAGE_ipq-wifi-motorola|VERSION_NUMBER|SIGNED_PACKAGES" .config
  if [ ! -s key-build ]; then
    echo "== tools + toolchain, then the usign/ucert host tools (package/system/*, need the tools stage first)"
    make -j12 tools/install toolchain/install 2>&1 | tail -5
    make -j12 package/system/usign/host/compile package/system/ucert/host/compile 2>&1 | tail -5
    echo "== generating usign build key"
    staging_dir/host/bin/usign -G -s key-build -p key-build.pub -c "neon MH7021 build key $(date +%F)"
    staging_dir/host/bin/ucert -I -c key-build.ucert -p key-build.pub -s key-build
    chmod 600 key-build
  fi
  make -j12 2>&1 | tail -30 || make -j1 V=s 2>&1 | tail -80
  cd bin/targets/ipq40xx/generic
  [ -s sha256sums.sig ] || ../../../../staging_dir/host/bin/usign -S -m sha256sums -s ../../../../key-build -x sha256sums.sig
  echo "== signature checks"
  ../../../../staging_dir/host/bin/usign -V -m sha256sums -p ../../../../key-build.pub -x sha256sums.sig && echo "sha256sums.sig OK"
  for f in *motorola_mh7021*sysupgrade.bin; do ../../../../staging_dir/host/bin/fwtool -i /dev/null "$f" && echo "$f: metadata present"; done
  ls ../../../../*.pem ../../../../key-build* 
'
ls -la $T/bin/targets/ipq40xx/generic/ | grep -E "mh7021|sha256sums"
echo "board files in the staged rootfs (24468 / 12244 bytes = ours):"
ls -la $T/build_dir/target-*/root-ipq40xx/lib/firmware/ath10k/QCA4019/hw1.0/board-2.bin $T/build_dir/target-*/root-ipq40xx/lib/firmware/ath10k/QCA9888/hw2.0/board-2.bin 2>/dev/null || echo "(root-ipq40xx not found -- check the build output)"
